package com.gs.HumanTech.dao;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

@Component
public class DBConnection {

    @Value("${spring.datasource.url}")
    private String db;

    @Value("${spring.datasource.username}")
    private String user;

    @Value("${spring.datasource.password}")
    private String password;

    public Connection getConnection() {
        try {
            Connection conn = DriverManager.getConnection(db, user, password);
            System.out.println("Conectado com sucesso");
            return conn;
        } catch (SQLException e) {
            throw new RuntimeException("Erro ao conectar ao banco", e);
        }
    }

    public void startDB() {

        String createTableCandidato = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE candidatos (
                        id_candidato NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR2(100),
                        email VARCHAR2(100),
                        cidade VARCHAR2(100),
                        pais VARCHAR2(50)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """;

        String createTableVaga = """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE vagas (
                        id_vaga NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        titulo VARCHAR2(100),
                        tipo_trabalho VARCHAR2(100),
                        salario NUMBER(10,2),
                        descricao VARCHAR2(4000)
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        """;

        // Adicione estes quando você tiver criado as strings:
        // stmt.execute(createTableUser);
        // stmt.execute(createTableCourse);

        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {

            stmt.execute(createTableCandidato);
            stmt.execute(createTableVaga);

            System.out.println("Tabelas criadas/verificadas com sucesso!");

        } catch (SQLException e) {
            throw new RuntimeException("Erro ao criar tabelas", e);
        }
    }
}
